name: Release

env:
  POETRY_VERSION: "1.6.1"
  PYTHON_VERSION: "3.11"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+rc[0-9]+"
      - "[0-9]+.[0-9]+[ab][0-9]+"

jobs:
  release:
    name: Release to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Set up Poetry
        run: |
          pip install poetry==${{ env.POETRY_VERSION }}

      # Note: If build and publish steps are ever separated, the version must
      #       be set before building
      - name: Publish package
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry version "${GITHUB_REF#refs/*/}"
          poetry publish --build

      - name: Update changelog
        run: |
          TAG_NAME="${GITHUB_REF#refs/*/}"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git fetch origin main

          poetry run -- rooster release --no-update-pyproject
          git checkout -b "release/changelog-$TAG_NAME"
          git commit -am "Update changelog for $TAG_NAME"
          git push --set-upstream origin HEAD

          gh pr create \
            --fill \
            --body "See: https://github.com/zanieb/rooster/releases/tag/$TAG_NAME"

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
